export const MAIN_ROUTE = "/"
export const ARTWORK_ROUTE = "/artwork/:id"
export const ARTWORK_ROUTE_LESS_ID = "/artwork/"
export const PROFILE_ROUTE = "/:id"
export const PROFILE_ROUTE_LESS_ID = "/"
export const CREATION_ROUTE = "/creation/:id"
export const CREATION_ROUTE_LESS_ID = "/creation/"